name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: github-repository to lowercase
        run: |
          echo "REPOSITORY_LOWERCASE=${REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          REPOSITORY: "${{ github.repository }}"

      - name: Build and push to Docker registries
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_LOWERCASE }}:latest

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK }}
          webhook_secret: ${{ secrets.DEPLOY_SECRET }}
          silent: true
